# Generated by Django 5.2 on 2025-05-31 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='image_path',
            field=models.CharField(blank=True, default='images/default-place.jpg', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='placesvisited',
            name='feedback',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='placesvisited',
            name='mark',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True, verbose_name='Оценка'),
        ),
    ]
