# Generated by Django 5.2 on 2025-05-31 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0003_alter_placesvisited_feedback_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="place",
            name="image_path",
        ),
        migrations.AddField(
            model_name="place",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="places/images/",
                verbose_name="Изображение",
            ),
        ),
    ]
