# Generated by Django 5.2 on 2025-05-31 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_alter_place_image_path_alter_placesvisited_feedback_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='image_path',
            field=models.ImageField(blank=True, default='images/default-place.jpg', null=True, upload_to='places/images/'),
        ),
    ]
