# Generated by Django 5.2 on 2025-05-31 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0004_remove_place_image_path_place_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="image",
            field=models.ImageField(
                blank=True,
                default="images/default-place.jpg",
                null=True,
                upload_to="images/",
                verbose_name="Изображение",
            ),
        ),
    ]
