# Generated by Django 5.2 on 2025-05-31 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0005_alter_place_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rating",
            name="place",
        ),
        migrations.AlterField(
            model_name="place",
            name="image",
            field=models.ImageField(
                blank=True,
                default="images/default-place.jpg",
                null=True,
                upload_to="places/images/",
            ),
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mark", models.IntegerField(blank=True, null=True)),
                ("comment", models.TextField(blank=True, null=True)),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="places.place"
                    ),
                ),
            ],
            options={
                "db_table": "reviews",
            },
        ),
        migrations.DeleteModel(
            name="Comment",
        ),
        migrations.DeleteModel(
            name="Rating",
        ),
    ]
