# Generated by Django 5.2 on 2025-05-31 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='place',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
