# Generated by Django 5.2 on 2025-05-31 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0006_remove_rating_place_alter_place_image_review_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="place",
            old_name="image",
            new_name="image_path",
        ),
    ]
