# Generated by Django 5.2 on 2025-05-31 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_comment_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
