# Generated by Django 5.2 on 2025-05-31 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0007_rename_image_place_image_path"),
    ]

    operations = [
        migrations.RenameField(
            model_name="place",
            old_name="image_path",
            new_name="image",
        ),
    ]
