# Generated by Django 5.2 on 2025-05-31 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0008_rename_image_path_place_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="short_description",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
